# Generated by Django 5.2.7 on 2025-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
